### ISSUE TITLE
Add iyenaland language.

### ISSUE THREAD

**Issue by iyenal** [Apfel/hello-world-everywhere#4]
I am very disappointed. No iyenish language? That should be one of the first languages supported.
Apfel u are a bad boi.

**Comment by Apfel** [comment]
Heck why am i abused for fun

**Comment by Apfel** [comment]
@iyenal i need an example for iyenish

**Comment by DismissedGuy** [comment]
```dismissed
dismissable class get_dismissed() {
  raise DismissedException from dismissals
}
```

**Comment by Apfel** [comment]
That lang doesnt look very good so no iyenish
